builds:
- env:
  - CGO_ENABLED=0
  id: "be-logreport"
  binary: be-logreport-{{ .Os }}-{{ .Arch }}
  main: ./main.go
  goos:
    - windows
    - darwin
  goarch:
    - 386
    - amd64
  ignore:
    - goos: darwin
      goarch: 386
archives:
  - 
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      windows: Windows
      386: x86
      amd64: x64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'